<?php

declare(strict_types=1);

namespace NewPlayerMC;

use muqsit\invmenu\InvMenuHandler;
use NewPlayerMC\commands\SlotMachineCommand;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\SingletonTrait;

class Main extends PluginBase {
    use SingletonTrait;

    protected function onEnable(): void
    {
        self::$instance = $this;

        if(!InvMenuHandler::isRegistered()){
            InvMenuHandler::register($this);
        }

        $this->getServer()->getCommandMap()->register("slotmachine", new SlotMachineCommand());
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

}
