<?php

declare(strict_types=1);

namespace NewPlayerMC;

use muqsit\invmenu\InvMenuHandler;
use NewPlayerMC\commands\SlotMachineCommand;
use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\Config;
use pocketmine\utils\SingletonTrait;

class Main extends PluginBase implements Listener {
    use SingletonTrait;

    private Config $save;

    protected function onEnable(): void
    {
        self::$instance = $this;

        @mkdir($this->getDataFolder());

        if(!InvMenuHandler::isRegistered()){
            InvMenuHandler::register($this);
        }

        $this->getServer()->getCommandMap()->register("slotmachine", new SlotMachineCommand());

        BetsManager::getInstance()->loadHistory();
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    protected function onDisable(): void
    {
        parent::onDisable(); // TODO: Change the autogenerated stub

        BetsManager::getInstance()->saveHistory();
    }

}
